### PR TITLE
Initial API style guide

### PR DESCRIPTION
**Pull request by jeremyw**
@mdenomy @gwithers @matrixsc @thegreatape @joelind @DanLuchi @kdsingharneja @atkinss Please review/add content

### CODE REVIEW

**Comment by joelind** [comment]
A few quick suggestions:

Routes: use `resource :users, only: [:whatever, :is, :needed]`
Nesting: Avoid deep nesting

**Comment by kdsingharneja** [comment]
Also, prefer namespace for organizing controllers. For e.g for admin/setup we should use single namespace -> setup

**Comment by jeremyw** [comment]
@joelind @kdsingharneja Should there be a guideline for "deep" nesting? Does nesting only apply to nested resources, or namespaces as well? `/api/v1/admin/setup` already has 4 elements in the path before we've gotten to a resource.

**Comment by thegreatape** [comment]
This is covered in the HTTP Verb article you linked, but I think it's worth emphasizing that GETs should always be idempotent read-only operations.

**Comment by joelind** [comment]
@jeremyw I think that instance identifiers are more what I am referring to. `/api/v1` should not count at all. If `admin` is a namespace, then that doesn't count either. But `users/:user_id/folders/:folder_id/documents/:document_id` is excessive. I think a good general rule I've seen would be no more than 2 identifiers deep.

What do the rest of you think?

**Comment by thegreatape** [comment]
@joelind @jeremyw Perhaps a more general of thumb might be "don't use ActiveRecord relationships for nesting"?

**Comment by joelind** [comment]
@thegreatape well, I mean, `GET /folders/:folder_id/documents` makes sense, as does `POST /folders/:folder_id/documents`, but *NOT* `GET /folders/:folder_id/documents/:document_id`

**Comment by thegreatape** [comment]
@joelind Hmm, you're right. Does "one id per url" make more sense?

**Comment by jeremyw** [comment]
Agreed, assuming we have access control/authorization/scoping in place so we're not just fetching a document by any `:document_id` we're given. This has not historically been the case.

**Comment by thegreatape** [comment]
Do we have any existing conventions in place for whether we serialize related objects or embed their ids?

**Comment by joelind** [comment]
@jeremyw right. I think scoping by project is a bit screwed up now. (there's a persisted `active_project_id` on the user which is sometimes use but this state should be in the URL)

**Comment by joelind** [comment]
@thegreatape you mean for embedding in responses? I'd be surprised if there are existing conventions, but would love to chat about pros/cons for this stuff (especially for mobile APIs)

**Comment by jeremyw** [comment]
@thegreatape I think that's mostly use-case dependent.

**Comment by thegreatape** [comment]
@joelind Yep, whether the response has `related_thing: { ... }` or `related_thing_id: 12`. There are some interesting tradeoffs either way, generally either server-side efficiency or more HTTP requests for the client. 

@jeremyw Agreed, it's not something to decide in a vacuum. It'd be nice if we were able to be consistent about it, though.

**Comment by jeremyw** [comment]
ActiveModel::Serializer has default behavior that we can just co-op as our style.

**Comment by mdenomy** [comment]
:+1:

**Comment by atkinss** [comment]
:+1:  on the guide and the dialogue around embedded child entities, which probably warrants more discussion and maybe even an overarching rule of thumb.

**Comment by kdsingharneja** [comment]
@jeremyw Of course, 4 element is not ideal, but again it is the use of the namespace we have to watchout for. For example, api/v1 is something we came up with, perhaps due to it being a public api. I have never seen version numbers in api urls. Hence, IMHO version numbers should not be in namespaces, at least not "v1", but again that is spilt milk under the bridge

As for name spacing, from what I understood is good from controllers point of perspective, where they are mainly inward facing resources and APIs do not have to be shared. For example when we refactor issues (only a Field thing), it would be good to create a namespace around it, let each different sub view around it be a sub namespace, but not "v1" nomenclature. So just 2 or max 3 level. If it a very specific 4th level is needed, then we should look at the design again.

**Comment by jeremyw** [comment]
@kdsingharneja Let's forget what we have (which is probably 4 or 5 distinct APIs with very different designs) and figure out what we want. Legacy APIs can be removed, deprecated, and/or mapped to new APIs.

We can punt on the versioning discussion until we have a need for versioning. API namespacing and controller namespacing are not necessarily coupled -- what would be a few ideal API URIs regardless of Rails implementation details?

**Comment by jeremyw** [comment]
Updated PR with some additional content. Remove versioning stuff for now because I think it warrants some consideration.

**Comment by joelind** [comment]
:+1:

**Comment by thegreatape** [comment]
:ship: it.

**Pull request merged**
